### ISSUE TITLE
Code License 

### ISSUE THREAD

**Issue by mehtadushy** [tstandley/taskgrouping#11]
Hi

Could you please make it explicit what license the code is made available under?

**Comment by mehtadushy** [comment]
Hi

Bumping this. Would it be possible to clarify the license under which the code is made available? I would like to build upon your work, but am not able to proceed without knowing the license.

Best

**Comment by tstandley** [comment]
Hey @mehtadushy. Sorry for the late reply. Code is now under the MIT licence.

**Comment by mehtadushy** [comment]
Thanks! :)
